### ISSUE TITLE
got a strange error

### ISSUE THREAD

**Issue by ProFireDev** [stanleyjzheng/dcp-bridgehacks#1]
here check out this recording of it running

[https://www.youtube.com/watch?v=xvFZjo5PgG0](https://www.youtube.com/watch?v=xvFZjo5PgG0)

**Comment by stanleyjzheng** [comment]
You got me, LOL.

**Comment by ProFireDev** [comment]
> You got me, LOL.

of course, I had to get you back after the wonderful notification from dev post
